<?php
namespace V2\Controller;

use V2\Service\PlayerService;

class PlayerController extends BaseController{

    protected $playerServer;

    public function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $operator_id = I('operatorid');
        $operator_info = D('Operator')->find($operator_id);
        $userinfoDB = '';
        if($operator_info['is_diy'] == 1){
            $userinfoDB = $operator_info['diy_db_name'];
        }else{
            $userinfoDB = 'public_laohu';
        }
        $this->playerServer = new PlayerService($userinfoDB);
    }

	// 玩家账号注册
    public function register_player(){

		$param = I('post.');

		$result = $this->playerServer->register($param);

		$this->response($result,'json');

    }

	// 获取玩家信息
	public function get_info(){

		$param = I('post.');

		$result = $this->playerServer->get_info($param);

		$this->response($result,'json');
	}

	// 修改玩家登录密码
	public function update_password(){

		$param = I('post.');

		$result = $this->playerServer->update_pwd($param);

		$this->response($result,'json');
	}

	// 玩家账号冻结
	public function frozen_player(){

		$param = I('post.');

		$result = $this->playerServer->frozen($param);

		$this->response($result,'json');

	}
	//设置玩家vip等级
	public function set_viplev(){

		$param = I('post.');

		$result = $this->playerServer->set_viplevel($param);

		$this->response($result,'json');

	}

	// 获取用户投注记录
	public function get_all_spindata(){

		$param = I('post.');

		$result = $this->playerServer->get_all_spindata($param);

		$this->response($result,'json');
	}

	// 玩家充值
	public function deposit_gold(){

		$param = I('post.');

		$result = $this->playerServer->deposit($param);

		$this->response($result,'json');
	}

	// 玩家取现
	public function withdrawal_gold(){

		$param = I('post.');

		$result = $this->playerServer->withdrawal($param);

		$this->response($result,'json');
	}

	// 获取玩家订单状态
	public function get_order_status(){

		$param = I('post.');

		$result = $this->playerServer->get_order_status($param);

		$this->response($result,'json');
	}
}
